shop/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views


app_name ="shop"

urlpatterns = [
    url(r'^$', views.ShopBookList.as_view(), name='index'),
    url(r'^category/(?P<slug>[\w-]+)$', views.BookList.as_view(), name='post'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetail.as_view(), name='detail'),
    url(r'^auth/register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^search/?$', views.ProfileSearchView.as_view(), name='search'),
    url(r'^', views.ShopBookList.as_view(), name='index'),

]

shopapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shop/',include('shop.urls')),
    url(r'^',include('shop.urls')),
]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=52)
    describe = models.TextField()
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    year = models.IntegerField()
    photo = models.ImageField(upload_to='images')
    price = models.IntegerField(null=True)

    def __str__(self):
        return self.title




class Author(models.Model):
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=40, unique=True)
    slug = models.SlugField(max_length=50, null=True)

    def __str__(self):
        return self.name



    #def get_absolute_url(self):
        #return reverse('post', kwargs={'slug': self.slug, 'id': self.id})

shop/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class UserForm(UserCreationForm):


    class Meta:
        model= User
        fields = ('username', 'email', 'password1','password2')

shop/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import  AuthenticationForm
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from .models import Book, Author, Category
from django.views import generic
from django.views.generic import View
from .forms import UserForm





app_name = 'shop'

# Create your views here.
class ShopBookList(generic.ListView):
    template_name = "index.html"
    model = Book
    paginate_by =9
    def get_context_data(self, **kwargs):
        context = super(ShopBookList, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        contacts = Book.objects.filter(year=2018)
        context['name_category'] = 'Новинки'
        paginator = Paginator(contacts, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            file_exams = paginator.page(page)
        except PageNotAnInteger:
            file_exams = paginator.page(1)
        except EmptyPage:
            file_exams = paginator.page(paginator.num_pages)

        context['contacts'] = file_exams

        return context


class BookList(generic.ListView):
    template_name = "index.html"
    model = Book
    paginate_by = 9
    def get_context_data(self, **kwargs):
        context = super(BookList, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        contacts = Book.objects.filter(category__slug=self.kwargs.get('slug'))
        context['name_category'] = Category.objects.get(slug=self.kwargs.get('slug'))
        paginator = Paginator(contacts, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            file_exams = paginator.page(page)
        except PageNotAnInteger:
            file_exams = paginator.page(1)
        except EmptyPage:
            file_exams = paginator.page(paginator.num_pages)

        context['contacts'] = file_exams
        return context


class BookDetail(generic.DetailView):
    model = Book
    template_name = 'detail_book.html'

    def get_context_data(self, **kwargs):
        context = super(BookDetail, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class UserFormView(View):
    form_class = UserForm
    template_name = 'register.html'
    categories = Category.objects.all()

    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form, 'categories': self.categories})

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('shop:index')

        return render(request,self.template_name,{'form':form})


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = "/shop"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/shop")



class ProfileSearchView(generic.ListView):
    template_name = 'index.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super(ProfileSearchView, self).get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['contacts'] = self.model.objects.filter(title__icontains=query)
        context['query'] = query
        context['name_category'] = "Результаты Вашего поиска:'{}'".format(query)
        context['categories'] = Category.objects.all()
        return context

shop/templates/category.html
{% block category %}
	<div class="sub-cate">
				<div class=" top-nav rsidebar span_1_of_left">
					<h3 class="cate">КАТЕГОРИИ</h3>
					{% for category in categories %}
		  <ul class="menu">
		<li class="item1"><a href="{% url 'shop:post' category.slug %}">{{category}} </a></li>
	      </ul>
					{% endfor %}
				</div>
	</div>
	</div>

{% endblock %}

shop/templates/detail_book.html
{% extends 'basic.html' %}

{% load static %}

{% block content %}
	 	<div class="grid-product">
	      <div class="single_grid">
					<div class="grid images_3_of_2">
						<img  src="{% static '/'%}{{book.photo}}" class="img-responsive" >
							 <div class="clearfix"> </div>
					</div>
						  <div class="desc1 span_3_of_2">
                          <div class="left-n "></div>
							  <h3><strong>{{ book }}</strong></h3>
			                  <h6><strong>Цена:</strong>{{book.price}}</h6>
							  <h6><strong>Автор:</strong> {{ book.author }}</h6>
							  <h6><strong>Категория:</strong> {{book.category}}</h6>
								  <h6><strong>Год:</strong> {{ book.year}}</h6>

						  </div>
			   	      <div class="share"></div>
		  </div>
          	          <div class="clearfix"> </div>
		</div>
							<div class="toogle">
								<h3 class="m_3">Описание книги</h3>
								<p class="m_text">{{book.describe}}</p>
							 </div>

		</div>



{% include 'category.html'%}

{% endblock %}

shop/templates/index.html
{% extends 'basic.html' %}
{% load static %}

	{% block content %}
<div class="grid-product">
	<h2>{{ name_category }}</h2>
	{% if contacts %}
	   {% for book in contacts %}
			<div class="  product-grid">
				<div class="content_box"><a href="{% url 'shop:detail' book.id %}">
					<div class="left-grid-view grid-view-left">
						<img src="{% static '/'%}{{book.photo}}" class="img-responsive watch-right" alt=""/>
							<div class="mask">
								<div class="info"></div>
							</div>
							  </a>
							<h4><a href="{% url 'shop:detail' book.id %}" class="text-center" >{{book.title}}</a></h4>
				    </div>
							 <p class="text-primary">Год:  {{book.year}}</p>
							 <p class="text-left">Цена: {{book.price}}</p>
				</div>

    </div>
    {% endfor %}
			<div class="clearfix"> </div>
    {% else %}
    <h2> По Вашему запросу ничего не найдено </h2>
    {% endif%}



{% include 'pagination.html'%}
</div>
</div>
{% include 'category.html'%}



{% endblock %}

shop/templates/login.html
{% extends 'basic.html'%}

{% block content %}
       	   <div class="account_grid">
			   <div class=" login-right">
			  	<h3>Войти</h3>
                 <form method="post">
                      {% csrf_token %}
                      {{ form.as_p }}
                    <input type="submit" value="login">
                  </form>
               </div>
           </div>
</div>
{% include 'category.html' %}
{% endblock %}

shop/templates/pagination.html
{% block pagination %}
{% if is_paginated %}
    <nav aria-label="Page navigation">   <ul class="pagination">
    {% if contacts.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page=1" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">begin</span>
      </a>
    </li>   {% endif %}

    {% for n in contacts.paginator.page_range %}
      {% if contacts.number == n %}
        <li class="page-item active">
          <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
        </li>
      {% elif n > contacts.number|add:'-3' and n < contacts.number|add:'3' %}
        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
      {% endif %}
    {% endfor %}

    {% if contacts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ contacts.paginator.num_pages }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">end</span>
        </a>
      </li>
      {% endif %}   </ul> </nav>
{% endif %}
{% endblock %}

shop/templates/register.html
{% extends 'basic.html'%}
{% block content %}
<div class="register">
  <form method="post">
	  <div class="  register-top-grid">
		  <h2>Регистрация</h2>

    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
		  {{ field }}
        {% if field.help_text %}
          <small style="color: grey"></small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
          <input type="submit" value="login">

	  </div>
</form>

</div>
</div>

{% include 'category.html'%}

{% endblock %}

shop/templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
<p>Found {{ books|length }} book{{ books|pluralize }}.</p>
<ul>
    {% for book in books %}
    <li>{{ book.title }}</li>
    {% endfor %}
</ul>
{% else %}
<p>No books matched your search criteria.</p>
{% endif %}

shopapp/templates/basic.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Bookshop</title>

	<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--theme-style-->
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--fonts-->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<!--//fonts-->
<script src="{% static 'js/jquery.min.js' %}"></script>


<!--script-->
</head>
<body>
	<!--header-->
	<div class="header">
		<div class="top-header">
			<div class="container">
				<div class="top-header-left">
					<div class="clearfix"> </div>
				</div>
				<div class="top-header-right">
					<div class="clearfix"> </div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="bottom-header">
			<div class="container">
				<div class="header-bottom-left">
					<div class="logo">
						<a href="index.html"><img src="{% static 'images/logo.png'%}" alt=" " /></a>
					</div>
                   <div class="search">

						<form type="get" action="{% url 'shop:search' %}">
                           <input type="search" id="q" name="q" placeholder="Search..."/>
                        </form>
				</div>

					<div class="clearfix"> </div>
				</div>
				<div class="header-bottom-right">
							<ul class="login">
								 {% if user.is_authenticated %}
										<li><a href="{% url 'shop:logout' %}"><span> </span>Привет, {{ user.username  }}!(выйти)</a> |</li>
									{% else %}
										<li><a href="{% url 'shop:login' %}"><span> </span>Войти</a>|</li>
								{% endif %}
								<li ><a href="{% url 'shop:register'%}"><span> </span>РЕГИСТРАЦИЯ</a></li>
							</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!---->
	<!-- start content -->
	<div class="container">

	<div class="women-product">
		<div class=" w_content">

		</div>
		<!-- grids_of_4 -->

		{% block content %}{% endblock %}

	</div>

						<!--initiate accordion-->



	<div class="clearfix"> </div>
</div>
	<!---->
	<div class="footer">
		<div class="footer-top">
			<div class="container">
				<div class="latter-right">
					<p></p>
					<ul class="face-in-to">
						<li><a href="#"><span> </span></a></li>
						<li><a href="#"><span class="facebook-in"> </span></a></li>
						<div class="clearfix"> </div>
					</ul>
					<div class="clearfix"> </div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="container">
				<div class="footer-bottom-cate">
					<h6>Доставка</h6>
					<p>Доставим Ваш заказ в любой город Украины.
						Способы доставки: курьером, Нова Пошта, Автолюкс, Интайм, Укрпочта, самовывоз из офиса.
						Все заказы пакуются супернадежно и застрахованы</p>

				</div>
				<div class="footer-bottom-cate bottom-grid-cat">
					<h6> ОПЛАТА </h6>
					<p>Оплата заказа любым удобным для Вас способом</p>
				</div>
				<div class="footer-bottom-cate">
					<h6>О НАС</h6>
					<p>BOOKSHOP –  интернет-магазин который создан с целью получения практического опыта
					разработки на Django</p>
				</div>

				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
</body>
</html>